development:
  host: localhost
  database: kindness_card_development

test:
  host: localhost
  database: kindness_card_test

production:
  uri: mongodb://heroku:ab2h1okrodke2931ahwz2q@flame.mongohq.com:27094/app482517