defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: kindness_card_development

test:
  <<: *defaults
  database: kindness_card_test

production:
  uri: <%= ENV['MONGOHQ_URL'] %>
