require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LearnsController do

  def mock_learn(stubs={})
    @mock_learn ||= mock_model(Learn, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all learns as @learns" do
      Learn.stub(:all) { [mock_learn] }
      get :index
      assigns(:learns).should eq([mock_learn])
    end
  end

  describe "GET show" do
    it "assigns the requested learn as @learn" do
      Learn.stub(:find).with("37") { mock_learn }
      get :show, :id => "37"
      assigns(:learn).should be(mock_learn)
    end
  end

  describe "GET new" do
    it "assigns a new learn as @learn" do
      Learn.stub(:new) { mock_learn }
      get :new
      assigns(:learn).should be(mock_learn)
    end
  end

  describe "GET edit" do
    it "assigns the requested learn as @learn" do
      Learn.stub(:find).with("37") { mock_learn }
      get :edit, :id => "37"
      assigns(:learn).should be(mock_learn)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created learn as @learn" do
        Learn.stub(:new).with({'these' => 'params'}) { mock_learn(:save => true) }
        post :create, :learn => {'these' => 'params'}
        assigns(:learn).should be(mock_learn)
      end

      it "redirects to the created learn" do
        Learn.stub(:new) { mock_learn(:save => true) }
        post :create, :learn => {}
        response.should redirect_to(learn_url(mock_learn))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved learn as @learn" do
        Learn.stub(:new).with({'these' => 'params'}) { mock_learn(:save => false) }
        post :create, :learn => {'these' => 'params'}
        assigns(:learn).should be(mock_learn)
      end

      it "re-renders the 'new' template" do
        Learn.stub(:new) { mock_learn(:save => false) }
        post :create, :learn => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested learn" do
        Learn.stub(:find).with("37") { mock_learn }
        mock_learn.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :learn => {'these' => 'params'}
      end

      it "assigns the requested learn as @learn" do
        Learn.stub(:find) { mock_learn(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:learn).should be(mock_learn)
      end

      it "redirects to the learn" do
        Learn.stub(:find) { mock_learn(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(learn_url(mock_learn))
      end
    end

    describe "with invalid params" do
      it "assigns the learn as @learn" do
        Learn.stub(:find) { mock_learn(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:learn).should be(mock_learn)
      end

      it "re-renders the 'edit' template" do
        Learn.stub(:find) { mock_learn(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested learn" do
      Learn.stub(:find).with("37") { mock_learn }
      mock_learn.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the learns list" do
      Learn.stub(:find) { mock_learn }
      delete :destroy, :id => "1"
      response.should redirect_to(learns_url)
    end
  end

end
